// Shared inventory across all rental departments. Loaded by every catalog page;
// the cart looks items up here so one quote can span camera + lighting + grip.
const INVENTORY = [
  { dept:'lighting', id:'nanlux-2400b', cat:'big', brand:'Nanlux', tag:'LED · Key', name:'Nanlux Evoke 2400B', spec:'Bi-Color LED · 4000W HMI equivalent. Kit includes case, softbox, accessories.', day:575, photo:true },
  { dept:'lighting', id:'aputure-1200x', cat:'big', brand:'Aputure', tag:'LED · Key', name:'Aputure Storm 1200x', spec:'Bi-Color LED Kit · 1800W HMI eq · Fresnel 15–45°, barndoors, skid support.', day:350, photo:true },
  { dept:'lighting', id:'aputure-600d', cat:'big', brand:'Aputure', tag:'LED · Daylight', name:'Aputure 600d Pro', spec:'Daylight LED · 1200W HMI eq. 24\' weatherproof head cable. 50% on 2 V-Mounts.', day:185, photo:true },
  { dept:'lighting', id:'aputure-600x', cat:'big', brand:'Aputure', tag:'LED · Bi-Color', name:'Aputure 600x Pro', spec:'Bi-Color LED · 2700–6500K. 24\' weatherproof head cable. 50% on 2 V-Mounts.', day:225, photo:true },
  { dept:'lighting', id:'aputure-f10', cat:'big', brand:'Aputure', tag:'Fresnel', name:'Aputure F10 Fresnel + Barndoors', spec:'Fresnel attachment for 600-series fixtures. Barndoors included.', day:85, photo:true },
  { dept:'lighting', id:'aputure-spot', cat:'big', brand:'Aputure', tag:'Optic', name:'Aputure Spotlight Mount 36°', spec:'Projection optic for 600-series — gobo-ready focused beam.', day:65, photo:true },
  { dept:'lighting', id:'amaran-200x', cat:'mid', brand:'Amaran', tag:'LED · Compact', name:'Amaran 200x Bi-Color', spec:'Compact LED with barndoors, grid &amp; gel holder.', day:65, photo:true },
  { dept:'lighting', id:'aputure-60x', cat:'mid', brand:'Aputure', tag:'Focusing LED', name:'Aputure LS 60x Bi-Color', spec:'Focusing LED — adjustable beam angle. Small footprint, big punch.', day:55, photo:true },
  { dept:'lighting', id:'mc-pro', cat:'mid', brand:'Aputure', tag:'RGB · CRMX', name:'Aputure MC Pro RGB', spec:'CRMX-controllable RGBWW pocket light. Bubble diffuser included.', day:35, photo:true },
  { dept:'lighting', id:'mc', cat:'mid', brand:'Aputure', tag:'RGB · Pocket', name:'Aputure MC RGB', spec:'Pocket-sized RGBWW. Magnet mount, dual magnet light mount.', day:20, photo:true },
  { dept:'lighting', id:'b7c', cat:'mid', brand:'Aputure', tag:'Bulb · RGB', name:'Aputure B7C RGB Bulb', spec:'RGB practical bulb. E26 fit, app-controlled.', day:15, photo:true },
  { dept:'lighting', id:'c7r', cat:'mid', brand:'Godox', tag:'Bulb · RGB', name:'Godox C7R RGB Bulb', spec:'RGB practical bulb. Includes magnet mount &amp; bouncer.', day:15, photo:true },
  { dept:'lighting', id:'astera-titan', cat:'tubes', brand:'Astera', tag:'Tube · CRMX', name:'Astera Titan Tube 8-Light Kit', spec:'Battery-powered RGB LED tubes. CRMX, magnetic clips, custom grid.', day:400, photo:true },
  { dept:'lighting', id:'infinibar', cat:'tubes', brand:'Aputure', tag:'Tube · 4ft', name:'Aputure INFINIBAR PB12 4ft', spec:'4ft RGB LED tube. CRMX. Pixel-mappable.', day:75, photo:true },
  { dept:'lighting', id:'mega-6fc', cat:'tubes', brand:'Intellytech', tag:'RGB · Mat', name:'Intellytech Mega-6FC Litecloth 3.0', spec:'4\'×3\' RGB flexible mat. DMX, softbox &amp; grid, 26\' head extension.', day:275, photo:true },
  { dept:'camera', id:'red-komodo', photo:true, cat:'camera', brand:'RED', tag:'Cinema · 6K', name:'RED Komodo 6K Body Kit', spec:'Super-35 global-shutter 6K. Built up with cage, top/side plates, Wooden Camera V-mount plate &amp; NATO handles.', day:450 },
  { dept:'camera', id:'nucleus-m', cat:'camera', brand:'Tilta', tag:'Wireless FIZ', name:'Tilta Nucleus-M Follow Focus', spec:'Wireless follow focus — hand unit + motors. Rosette FIZ ready.', day:75, photo:true },
  { dept:'camera', id:'tentacle-sync', cat:'camera', brand:'Tentacle', tag:'Timecode', name:'Tentacle Sync E Mk2 Timecode', spec:'Bluetooth timecode with Komodo &amp; 5-pin LEMO cables.', day:25, photo:true },
  { dept:'camera', id:'pavo-set', cat:'lens', brand:'DZOFilm', tag:'Anamorphic · 2×', name:'PAVO 2× Anamorphic Set', spec:'Super-35 anamorphic primes — 28 · 40 · 75 · 135mm. T2.1–2.5, PL.', day:350, photo:true },
  { dept:'camera', id:'vespid-set', cat:'lens', brand:'DZOFilm', tag:'Prime Set', name:'VESPID Full-Frame Prime Set', spec:'T2.1 primes — 16 · 25 · 35 · 75mm with 4-lens hard case. PL.', day:175, photo:true },
  { dept:'camera', id:'laowa-ranger', photo:true, cat:'lens', brand:'Laowa', tag:'Cine Zoom', name:'Laowa Ranger 17–50mm T2.9', spec:'Super-35 lightweight cine zoom. PL-mount.', day:85 },
  { dept:'camera', id:'mirage-mattebox', cat:'lens', brand:'Tilta', tag:'Matte Box', name:'Tilta Mirage Matte Box + VND', spec:'Matte box with variable ND and 67–82mm adapter rings.', day:55, photo:true },
  { dept:'camera', id:'sachtler-18', photo:true, cat:'support', brand:'Sachtler', tag:'Fluid Head', name:'Sachtler Video 18 + Carbon Tripod', spec:'7–40 lb payload, 100mm bowl, SpeedLock carbon legs, ground spreader.', day:95 },
  { dept:'camera', id:'dana-dolly', photo:true, cat:'support', brand:'Dana Dolly', tag:'Dolly', name:'Dana Dolly Kit', spec:'Universal-track dolly with Mitchell riser &amp; slider stands.', day:85 },
  { dept:'camera', id:'rs3-pro', photo:true, cat:'support', brand:'DJI', tag:'Gimbal', name:'DJI RS 3 Pro Combo', spec:'10 lb gimbal with wireless lens &amp; gimbal control handles.', day:75 },
  { dept:'camera', id:'teradek-bolt6', photo:true, cat:'monitor', brand:'Teradek', tag:'Wireless Video', name:'Teradek Bolt 6 LT 750 Kit', spec:'Zero-delay 3G-SDI TX/RX to 750 ft. V-mount ready.', day:125 },
  { dept:'camera', id:'smallhd-1303', photo:true, cat:'monitor', brand:'SmallHD', tag:'Monitor · 13"', name:'SmallHD 1303 HDR 13"', spec:'Bright 13-inch HDR production monitor. Director-friendly.', day:85 },
  { dept:'camera', id:'smallhd-ultra5', cat:'monitor', brand:'SmallHD', tag:'Monitor · 5"', name:'SmallHD ULTRA 5', spec:'5-inch on-camera touchscreen. V-mount plate included.', day:55, photo:true },
  { dept:'camera', id:'portkeys-bm5', cat:'monitor', brand:'PortKeys', tag:'Monitor · Control', name:'PortKeys BM5WR 5.5"', spec:'5.5-inch monitor with camera control for RED Komodo.', day:45, photo:true },
  { dept:'grip', id:'high-roller', cat:'stands', brand:'American Grip', tag:'Overhead · 18′', name:'High Roller Overhead 18′ (×2)', spec:'Rocky Mountain leg, 4.5" grip head, Junior receiver, 60 lb max. Pair.', day:70, photo:true },
  { dept:'grip', id:'kupo-roller', cat:'stands', brand:'Kupo', tag:'Overhead · 19′', name:'Kupo High Roller 19′ (×2)', spec:'4.5" grip head, Junior receiver, 88 lb max. Pair.', day:70, photo:true },
  { dept:'grip', id:'combo-triple', cat:'stands', brand:'Matthews', tag:'Combo · 14′', name:'Combo Triple Riser 14′', spec:'Rocky Mountain leg, 68 lb max, Junior pin.', day:30, photo:true },
  { dept:'grip', id:'cstand-kit', cat:'stands', brand:'Matthews', tag:'C-Stand · ×6', name:'40&quot; C-Stand Package (×6)', spec:'Grip head &amp; arm — sliding-leg and turtle-base. Six stands.', day:90, photo:true },
  { dept:'grip', id:'flag-kit', cat:'grip', brand:'Matthews', tag:'Flags · Nets', name:'Scrim &amp; Flag Kit 24×36', spec:'Single/double scrim, silks, solid, floppy — studio + run-n-gun kits.', day:55, photo:true },
  { dept:'grip', id:'floppy-cutters', cat:'grip', brand:'Matthews', tag:'Cutters · 4×4', name:'Floppy Cutters 4′×4′ (×2)', spec:'Top-hinge floppies, open to 4×8. Pair.', day:36, photo:true },
  { dept:'grip', id:'clamp-package', cat:'grip', brand:'Matthews', tag:'Clamps', name:'Grip &amp; Clamp Package', spec:'Cardellini, Mafer, super clamps, cheeseboro, baby pins &amp; adapters.', day:65, photo:true },
  { dept:'grip', id:'apple-boxes', cat:'grip', brand:'Set', tag:'Apple Boxes', name:'Apple Box Set (full→pancake)', spec:'Full, half, quarter and eighth — four of each.', day:35, photo:true },
  { dept:'grip', id:'sandbags', cat:'grip', brand:'Set', tag:'Sandbags', name:'Sandbag Package', spec:'10, 15, 25 and 35 lb bags — full set for safe rigging.', day:40, photo:true },
  { dept:'grip', id:'overhead-12', cat:'frames', brand:'Matthews', tag:'Overhead · 12×12', name:'12×12 / 6×6 Overhead Frame System', spec:'Aluminum pipe, ears, connectors &amp; corners. Breaks down to 6×6.', day:85, photo:true },
  { dept:'grip', id:'scrim-jim', cat:'frames', brand:'Westcott', tag:'Frame · 8×8', name:'Scrim Jim Cine 8′×8′', spec:'Modular frame, also builds 4×4. Cine clamps + bag.', day:50, photo:true },
  { dept:'grip', id:'overhead-skins', cat:'frames', brand:'Set', tag:'Skins · Set', name:'Overhead Skins Set', spec:'Grid cloth, muslin, UltraBounce, silk, magic cloth, single net &amp; digital green.', day:75, photo:true },
  { dept:'grip', id:'menace-arm', cat:'frames', brand:'Matthews', tag:'Arm', name:'Matthews Menace Arm Kit', spec:'Boom arm for placing overheads &amp; frames off-axis.', day:35, photo:true },
  { dept:'grip', id:'honda-eu2200', cat:'power', brand:'Honda', tag:'Generator', name:'Honda EU2200i Generator', spec:'2200W quiet inverter generator — clean power for set.', day:65, photo:true },
  { dept:'grip', id:'delta-pro', cat:'power', brand:'Aputure', tag:'Battery Station', name:'Aputure Delta Pro 3600W (×2)', spec:'3600W stations — 5 AC + 6 USB. Runs a 1200d 2+ hrs. Pair.', day:120, photo:true },
  { dept:'grip', id:'jackery-880', cat:'power', brand:'Jackery', tag:'Power Station', name:'Jackery 880 Power Station', spec:'Portable station with 3× 1000W AC outlets.', day:45, photo:true },
  { dept:'grip', id:'grip-truck-package', cat:'truck', brand:'Thunderstruck', tag:'Full Package', name:'Full Grip Truck Package', spec:'The entire 3-ton truck — all grip, stands, flags, frames, distro &amp; the electric package, delivered and operated.', day:1250, photo:true },
  { dept:'sound', id:'sd-633', cat:'recording', brand:'Sound Devices', tag:'Recorder · Mixer', name:'Sound Devices 633', spec:'6-input field mixer/recorder with timecode &amp; dual SD. ORCA bag and harness available.', day:85, photo:true },
  { dept:'sound', id:'orca-bag', cat:'recording', brand:'ORCA', tag:'Sound Bag', name:'ORCA OR-28 Bag + Harness', spec:'Audio bag with Porta Brace harness and K-Tek Stingray mixer bag.', day:25, photo:true },
  { dept:'sound', id:'sound-blanket', cat:'recording', brand:'Producers Choice', tag:'Blankets', name:'Sound Blankets (×2)', spec:'72×80&quot; moving/sound blankets — also double as a black flag or white bounce.', day:20, photo:true },
  { dept:'sound', id:'mkh50', cat:'mics', brand:'Sennheiser', tag:'Shotgun', name:'Sennheiser MKH 50', spec:'Supercardioid microphone with Rycote Super-Shield blimp kit.', day:55, photo:true },
  { dept:'sound', id:'boom-pole', cat:'mics', brand:'Ambient', tag:'Boom Pole', name:'Ambient QP480-SCM Boom Pole', spec:'Carbon-fiber boom pole, extends 11 ft, internal coiled cable. Auray holder.', day:25, photo:true },
  { dept:'sound', id:'cos11d', cat:'mics', brand:'Sanken', tag:'Lavalier', name:'Sanken COS-11D Lav', spec:'Broadcast lavalier — XLR, phantom or battery. Bubblebee concealer included.', day:30, photo:true },
  { dept:'sound', id:'dpa4061', cat:'mics', brand:'DPA', tag:'Lavalier', name:'DPA 4061 Lav', spec:'Low-sensitivity omni lavalier for louder sources.', day:30, photo:true },
  { dept:'sound', id:'lectro-smdwb', cat:'wireless', brand:'Lectrosonics', tag:'Wireless · Recorder', name:'Lectrosonics SMDWB', spec:'Wireless transmitter/recorder (B1: 537–614 MHz).', day:65, photo:true },
  { dept:'sound', id:'mm1', cat:'wireless', brand:'Sound Devices', tag:'Boom Preamp', name:'Sound Devices MM-1', spec:'Single-channel mic preamp for the boom operator.', day:35, photo:true },
  { dept:'sound', id:'tentacle-track-e', cat:'wireless', brand:'Tentacle', tag:'Timecode', name:'Tentacle TRACK E', spec:'Pocket timecode audio recorder for camera/sound sync.', day:20, photo:true }
];
